### ISSUE TITLE
Aplikace havaruje při pokusu o připojení ke smyšlenému serveru

### ISSUE THREAD

**Issue by kudlav** [kmzbrnoI/hJOPandroidDriver#15]
Při dodržení následujících kroků aplikace havaruje:
1. V záložce "Vyberte server" vytvořte libovolné smyšlené připojení (název:"1", server:"2")
2. Spojení uložte
3. Dlouhým stiskem na uložený server vyvolejte kontextovou nabídku
4. Zvolte "Připojit"
5. Aplikace havaruje

**Comment by horacekj** [comment]
Reprodukováno, kouknu na to.

**Comment by horacekj** [comment]
Release 0.7 by tuto chybu měl opravit, během pár hodin by se měl objevit jako aktualizace.
