### ISSUE TITLE
Doplnit návěstní opakovač

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPandroidDriver#22]
Bylo by velice hezké.

**Comment by horacekj** [comment]
Implementována podpora v protoklu a serveru. Zobrazovat opakovač a aktuální očekávanou rychlost.

**Comment by kudlav** [comment]
https://github.com/kmzbrnoI/hJOPandroidDriver/tree/expected-signal

ac88f18d020e23a391c16065ed8fe5077e9a3367 WIP: textual expected signal in portrait mode

**Comment by kudlav** [comment]
Funkční implementace v https://github.com/kmzbrnoI/hJOPandroidDriver/commit/d5bb18492f5ea7d90eba1b88399736c4e79a0cd1

Nutno zhodnotit UI/UX.
I na mém displeji se nevejdou celé následující návěsti:
 - Opakování návěsti Očekávej 40 km/h
 - Rychlost 40 km/h, opakování návěsti Výstraha

Zalomení by způsobilo nechtěné posunutí regulátoru rychlosti.
Návěst na nový řádek problém řeší ale plýtvá místem.
Poslední možností je dát tyto údaje pod regulátor rychlosti. Pokud ale uživatel posouvá/drží posuvník, na návěsti nevidí, zakrývá si jej prstem/rukou.

**Comment by kudlav** [comment]
Todo:

- [ ] přidat do landscape zobrazení
- [ ] po stisknutí zobrazit toast s názvem návěsti
- [ ] rekvence kmitání by optimálně mělo být okolo 54 kmitů za minutu

**Comment by kudlav** [comment]
Otestovat na zařízeních:
- [ ] 10
- [ ] 5.0.2
- [ ] 4.4.4

**Comment by horacekj** [comment]
Hotovo.
