### ISSUE TITLE
Při změně směru za jízdy zobrazí nesprávnou rychlost

### ISSUE THREAD

**Issue by kudlav** [kmzbrnoI/hJOPandroidDriver#25]
1. Převzít vlak do ručního řízení
2. Nastavit rychlost > 1km/h
3. Změnit směr

-> Aktuální rychlost je menší než původní, nejčastěji však 1 km/h, posuvník však zůstává v původní pozici.

Nutno otestovat skutečné chování s kolejištěm.

Zařízení:
- Samsung Galaxy A40 Android 10
- Vodafone Smart prime 6 Android 5.0.2
- Samsung Galaxy S4 mini Android 4.4.4

![hjopdrivererrorswap](https://user-images.githubusercontent.com/11516259/82664058-308b7d80-9c31-11ea-82cd-68de301c394c.jpg)

**Comment by kudlav** [comment]
Rychlost se bere z odpovědí serveru, z políčka info:
![44936f973d6de91266b2915b8fd4c21a 0](https://user-images.githubusercontent.com/11516259/82741037-8b66c700-9d4e-11ea-9cd2-035de86ebfbc.png)

**Comment by horacekj** [comment]
Server posílal špatné odpovědi. Opraveno na serveru, třeba upravit parsování, aby správně zobrazovalo rychlosti.
