### ISSUE TITLE
Odstranit train release aktivitu

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPandroidDriver#33]
Vůbec se nepoužívá.

**Comment by kudlav** [comment]
Mně by se líbilo release aktivitu zrušit a navíc do hlavního menu dát místo záložky Řízení vlaku konkrétní vlaky.
Uživatel bez vlaků by pak viděl pouze Žádost o vlak. Poskytlo by to hezký přehled. Nevím, jestli je to implementovatelné, ale jako vize hezké.

![Screenshot2](https://user-images.githubusercontent.com/11516259/94494074-8a5b1000-01ee-11eb-884f-f16eb24e0333.png)

**Comment by horacekj** [comment]
To vypadá rozumně. Název loko by pak nemusel být v CommonBoxu v aktivitě řízení, ale jako název aktivity.

**Comment by kudlav** [comment]
https://github.com/kmzbrnoI/hJOPandroidDriver/commit/450158cae8ad76d674fd7e8305b5bdeaf14bc0bf Aktivita odebrána, HV jsou v menu (zatím bez release tlačítek, asi by tam byly zbytečné).
CommonBox bude odebrán v samostatném commitu.

**Comment by horacekj** [comment]
Super. Ještě ně napadá taková věc: možná by stálo za to nějak v hamburgeru zvýraznit, které lokomotivy jsou v multitrakci (které řídíš zároveň). Napadá mě například místo tlačítka na release dát do hamburgeru kolečko:
* červené kolečko = loko stojí bez ručního řízení
* žádné kolečko = loko jede bez ručního řízení
* žluté kolečko = ruční řízení
* zelené kolečko = ruční řízení + v multitrakci

(Možná nějak změnit barvy nebo upravit jejich význam.)

Alternativně lze zobrazovat místo kolečka rychlost, to je možná intuitivnější, za to ale delší.

**Comment by kudlav** [comment]
Zkusil jsem to přidat k ikonce vlaku, tyto ikonky jsou ale monochromatické a nesmí obsahovat příliš detailů aby byly čitelné, takže návrh je takovýto:

- ruční řízení + v multitrakci
- ruční řízení
- loko jede bez ručního řízení
- loko stojí bez ručního řízení

![obrazek](https://user-images.githubusercontent.com/11516259/105645274-e3843900-5e9a-11eb-9628-ff4820e47675.png)

**Comment by horacekj** [comment]
Vypadá to moc pěkně.
