### ISSUE TITLE
Aktivita výběru serverů

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPandroidDriver#34]
* [x] Aktivita neškáluje přes celý display.
* [x] Refaktor na modernější styl?

**Comment by kudlav** [comment]
- [ ] code cleanup

Otestovat na zařízeních:
- [ ] 10
- [ ] 5.0.2
- [ ] 4.4.4

![Screenshot0](https://user-images.githubusercontent.com/11516259/94493539-2ab03500-01ed-11eb-958d-27dcad280d9b.png)
![Screenshot1](https://user-images.githubusercontent.com/11516259/94493536-2a179e80-01ed-11eb-8a64-d9da751483c7.png)
