### ISSUE TITLE
Zjednodušit multitrakci

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPandroidDriver#37]
Původní myšlenkou aplikace bylo, že uživatel může mít na mobilu více lokomotiv různých vlaků a ty řídit paralelně. Proto je při přebírání lokomotivy ve výchozím stavu checkbox "Multitrakce" odškrtnutý. Ukazuje se, že tento usecase není vůbec používaný. Pokud má uživatel více lokomotiv, prakticky vždycky je využívá v multitrakci.

Převzetí lokomotiv do multitrakce je uživatelsky nepřívětivé: je třeba u každé loko zaškrtnout "ruční řízení" a také "multitrakce". Navrhuji změnit chování aplikace tak, že checbox "Multitrakce" je rovnou zaškrtnutý při převzetí loko.

V multitrakci pak bude stačit převzít všechna loko do ručního řízení.

Dalším nápadem je se při převzetí jedné loko do ručního řízení (zašrknutí checboxu od uživatele) dotázat uživatele nějakým pop-up alertem, jestli nechce převzít i zbylé lokomotivy. Tady nechávám na zvážení, jestli implementovat, protože není úplně jasné, jak pak uživateli dát vědět, že se převzetí podařilo/nepodařilo.

**Comment by kudlav** [comment]
Jako posunovač můžu mít (a měl jsem) více lokomotiv, které nechci mít v
multitrakci.
Checkbox multitrakce bych ponechal nezatržený, ale pokud uživatel zatrhne
multitrakci, je jasné, že chce ovládat více lokomotiv a tedy po zatržení by
se mohl zobrazit dialog, ve kterém vybere zbývající lokomotivy a u těch se
mu zatrhne multitrakce i ruční řízení.

**Comment by horacekj** [comment]
To zní rozumně. Je pak třeba uživatele upozornit, pokud by se nepodařilo některou lokomotivu převzít na ruční řízení.

**Comment by kudlav** [comment]
Závislost ručního řízení a multitrakce opravena v https://github.com/kmzbrnoI/hJOPandroidDriver/commit/7b17c54ec592156e41faae61c398a4571bc36998

**Comment by kudlav** [comment]
Dialog při zapnutí multitrakce:
![Screenshot_20210207-144202_hJOP Driver](https://user-images.githubusercontent.com/11516259/107148404-1f1b0a80-6953-11eb-9ee4-6719d68141de.png)

Dialog při vypnutí multitrakce (pokud je v multitrakci nějaké další HV):
![Screenshot_20210207-144212_hJOP Driver](https://user-images.githubusercontent.com/11516259/107148393-16c2cf80-6953-11eb-8103-232236058547.png)

**Comment by kudlav** [comment]
Zatím se neupozorňuje, pokud se nepodaří převzít loko. Na to ještě kouknu. Ale zatím jsem na ošetření nenarazil ani co se týče checkboku ruční řízení v aktivitě řízení.

**Comment by kudlav** [comment]
Situace, kdy server pošle STOLEN nebo TOTAL false jsou reflektovány v GUI ale uživatel na ně není upozorněn. Možná by šlo řešit Toastem. Zatím implementovat nebudu, hodilo by se doplnit více informací do API dokumentace, kdy k těmto situacím dochází.

**Comment by kudlav** [comment]
Silně souvisí s #43
