### ISSUE TITLE
Řadit lokomotivy (v aktivitě řízení) podle adresy

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPandroidDriver#38]

**Comment by horacekj** [comment]
Tím je při používání konvence 9xxx = vůz mj. zajistí, že vozy jsou až na konci. Možná explicitně přidat klíč "vozy na konci"?

**Comment by kudlav** [comment]
Řazení dle adresy implementováno v 05320d52a5d602f33cb8a029c55a5d9bcd8eac97
