### ISSUE TITLE
Resume aktivity řízení loko zobrazí nekonzistentní funkce s vybranou lokomotivou

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPandroidDriver#39]

**Comment by horacekj** [comment]
Standardní řízení: (převzaty také další lokomotivy):
![Screenshot_20201204-170303](https://user-images.githubusercontent.com/12673442/101213421-a5c51a00-367a-11eb-8633-67b098357cdc.jpg)

Aplikace přesunuta na pozadí a znovu otevřena. Stav:

![Screenshot_20201204-170310](https://user-images.githubusercontent.com/12673442/101213426-a6f64700-367a-11eb-900c-c0bb08d4e4d0.jpg)

**Comment by horacekj** [comment]
Chová se stejně i při přetočení displaye (funkce se změní na funkce jiné lokomotivy)

**Comment by kudlav** [comment]
Tohle už jsem taky řešil, přesně takového chování eleminuje použítí ViewModel (View, ViewModel, Model), [[Google]](https://developer.android.com/topic/libraries/architecture/viewmodel), [[Medium]](https://medium.com/androiddevelopers/viewmodels-a-simple-example-ed5ac416317e). Třída aktivity by neměla uchovávat stav aplikace.

Určitě to půjde opravit i jinak, je to na zvážení, protože je to doporučenou architekturou a nové aplikace nemá cenu psát jinak, ale tady by to znamenalo úpravy.

Dřív nebo později (spíš později) se také budeme muset vypořádat s deprecated AsyncTask, buď přechodem na Kotlin (kam Google vývojáře směřuje) nebo na práci s procesy.

**Comment by kudlav** [comment]
Nakonec to bylo způsobeno přepsáním zvoleného vlaku při každém updateHW, problém by se projevoval nejen při obnovení obrazovky. Opraveno v 80c0394deb83df7087af8602d14fa8d2247f3bab
