### ISSUE TITLE
Vysvětlivky stavového kolečka

### ISSUE THREAD

**Issue by kudlav** [kmzbrnoI/hJOPandroidDriver#43]
V řízení vozidla vypsat vysvětlení kulaté ikonky pro stav vozidla (zelená fajfka, šedý otazník, ...). Buď pomocí krátkého stisku (tak se chová opakovač) nebo pomocí dlouhého stisku zobrazit Toast.

**Comment by horacekj** [comment]
Jsem určitě pro konzistentní chování s opakovačem, klidně krátký stisk.

**Comment by kudlav** [comment]
Zelená OK,
Oranžová = Stolen. Po kliknutí se pokusí získat zpět.
Červená = chyba při posledním příkazu.

Otázka je, co se dá dělat s lokomotivou, která je stolen. Možná se pokusit lokomotivu automaticky znovu získat a pokud se nepodaří, vzdát se jí?
Co se týče červené, chybu by chtělo uživateli více zdůraznit.

**Comment by horacekj** [comment]
Stolen = řízení lokomotivy ukradl nějaký jiný ovladač na fyzické sběrnici. Tato situace aktuálně nikde na klubovních kolejištích nemůže nastat. Nastala by tehdy, kdyby např. Multimaus připojená přímo k centrále začala řídit lokomotivu, kterou řídil ovladač.

Pokud je lokomotiva ukradena, určitě se ji nesnažit převzít zpět automaticky. Převzetí má inicializovat až uživatel. Myslím, že teď je to klikem právě na oranžové kolečko.

**Comment by kudlav** [comment]
Implementováno v bae2a11e18b20561bae0b526f572a836d37fc553

Zelené kolečko - při kliku toast _Řízení lokomotivy v pořádku_  
Oranžové kolečko - při kliku toast _Získávám zpět řízení lokomotivy_ a zároveň prosí server o řízení. Výsledek nevypisuje.  
Červené kolečko - jakmile nastane chyba a po kliknutí toast _Chyba posledního povelu_
