### ISSUE TITLE
Aktualizace seznamu funkcí

### ISSUE THREAD

**Issue by horacekj** [kmzbrnoI/hJOPandroidDriver#47]
Když server pošle aktualizovaná data hnacího vozidla (asi návěst na návěstním opakovači nebo rychlost), seznam funkcí hnacího vozidla sescrolluje úplně nahoru. Ruší, když má uživatel sescrollováno dolů. Ponechat aktuální pozici v seznamu.

**Comment by kudlav** [comment]
potvrzuji

**Comment by kudlav** [comment]
Opraveno v af05777ee4e440e99fa980504643170677aeb417

**Comment by kudlav** [comment]
Pozice zůstane zachována, scrolovat jde i během změny UI ale při změně dojde ke krátkému zobrazení scrollbaru funkcí.

**Comment by horacekj** [comment]
To zní v pohodě, za mě se může issue zavřít.
